{
  "type": "record",
  "name": "ProductReserved",
  "fields": [
    {"name": "event_id", "type": "string"},
    {"name": "event_type", "type": "string"},
    {"name": "timestamp", "type": "string"},
    {"name": "data", "type": {
        "type": "record",
        "name": "ProductReservedData",
        "fields": [
          {"name": "product_id", "type": "string"},
          {"name": "quantity", "type": "int"},
          {"name": "zone_id", "type": "string"},
          {"name": "order_id", "type": "string"}
        ]
      }
    }
  ]
}