{
  "type": "record",
  "name": "MovieEvent",
  "namespace": "online.cinema",
  "fields": [
    { "name": "event_id", "type": "string" },
    { "name": "user_id", "type": "string" },
    { "name": "movie_id", "type": "string" },
    { "name": "event_type", "type": { "type": "enum", "name": "EventType", "symbols": ["VIEW_STARTED", "VIEW_FINISHED", "VIEW_PAUSED", "VIEW_RESUMED", "LIKED", "SEARCHED"] } },
    { "name": "timestamp", "type": "long", "logicalType": "timestamp-millis" },
    { "name": "device_type", "type": { "type": "enum", "name": "DeviceType", "symbols": ["MOBILE", "DESKTOP", "TV", "TABLET"] } },
    { "name": "session_id", "type": "string" },
    { "name": "progress_seconds", "type": ["null", "int"], "default": null }
  ]
}