apiVersion: 1
datasources:
  - name: PostgreSQL
    uid: postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: analytics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
    isDefault: false