{
 "title": "Online Cinema Analytics",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "WITH first_activity AS (\r\n    SELECT\r\n        user_id,\r\n        min(toDate(timestamp)) AS cohort_day\r\n    FROM movie_events\r\n    GROUP BY user_id\r\n),\r\nuser_activity AS (\r\n    SELECT DISTINCT\r\n        user_id,\r\n        toDate(timestamp) AS activity_day\r\n    FROM movie_events\r\n),\r\ncohort_size AS (\r\n    SELECT\r\n        cohort_day,\r\n        count(DISTINCT user_id) AS total\r\n    FROM first_activity\r\n    GROUP BY cohort_day\r\n)\r\nSELECT\r\n    cohort_day AS \"Когорта\",\r\n    round(sumIf(1, activity_day = cohort_day + 0) / total * 100, 1) AS \"Day 0\",\r\n    round(sumIf(1, activity_day = cohort_day + 1) / total * 100, 1) AS \"Day 1\",\r\n    round(sumIf(1, activity_day = cohort_day + 2) / total * 100, 1) AS \"Day 2\",\r\n    round(sumIf(1, activity_day = cohort_day + 3) / total * 100, 1) AS \"Day 3\",\r\n    round(sumIf(1, activity_day = cohort_day + 4) / total * 100, 1) AS \"Day 4\",\r\n    round(sumIf(1, activity_day = cohort_day + 5) / total * 100, 1) AS \"Day 5\",\r\n    round(sumIf(1, activity_day = cohort_day + 6) / total * 100, 1) AS \"Day 6\",\r\n    round(sumIf(1, activity_day = cohort_day + 7) / total * 100, 1) AS \"Day 7\"\r\nFROM first_activity\r\nLEFT JOIN cohort_size USING (cohort_day)\r\nLEFT JOIN user_activity USING (user_id)\r\nGROUP BY cohort_day, total\r\nORDER BY cohort_day DESC   -- новые когорты сверху (можно ASC)"
    }
   ]
  },
  {
   "title": "Conversion Rate (Latest)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT metric_value FROM daily_metrics WHERE metric_name = 'conversion_rate' ORDER BY metric_date DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "DAU (Last 30 days)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT metric_date AS time, metric_value AS value FROM daily_metrics WHERE metric_name = 'DAU' AND metric_date >= CURRENT_DATE - INTERVAL '30 days' ORDER BY metric_date"
    }
   ]
  },
  {
   "title": "Top Movies (Latest Day)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT movie_id, views FROM top_movies WHERE metric_date = (SELECT MAX(metric_date) FROM top_movies) ORDER BY rank LIMIT 10"
    }
   ]
  }
 ]
}